### ISSUE TITLE
mapping tool needs to work properly

### ISSUE THREAD

**Issue by medhatelmasry** [medhatelmasry/voting-tool-cms#52]
MapBox mapping tool is built into application. The deployed version uses keys configured using azure-key-vault. Reliance on Azure needs to be decoupled. Perhaps the key should be entered as an ENVIRONMENT VARIABLE

There should be the flexibility to use any other tool.

**Comment by joecof** [comment]
In Progress

**Comment by reneilpascua** [comment]
THIS IS MY ISSUE NOW

**Comment by aiyuni** [comment]
I will work on this issue with @reneilpascua

**Comment by reneilpascua** [comment]
small progress made; fully blocked by issue #75

**Comment by reneilpascua** [comment]
after the resolution of issue #75, successfully removed azure key vault dependency by making changes to MapConfiguration.cs, MapsController.cs, mapbox-init.md

https://github.com/medhatelmasry/voting-tool-cms/pull/94
