### ISSUE TITLE
Generate DB entity relational diagrams dynamically [ SQL Server tool ]

### ISSUE THREAD

**Issue by medhatelmasry** [medhatelmasry/voting-tool-cms#53]
This may be already implemented via DgmlController. You'll need to go to that route to generate diagrams. i.e. http://dpyvweb.azurewebsites.net/dgml

Check out this article: http://blog.medhat.ca/2019/03/inspecting-your-net-classes-with-net.html

**Comment by BurdenKing** [comment]
Dgml controller was missing. 
I added a new dgml controller in the Api folder.
Now, when the user go to whateverhomeaddress / dgml. An entity.dgml file will be auto generated for downloading. The file can be also found in  the web folder. 
Install dgml editor feature / extension DgmlPowerTools  in visual studio 2019  to view the .dgml file as a graph or export the graph as a svg file.
