### ISSUE TITLE
Main navigation menu items incomplete

### ISSUE THREAD

**Issue by medhatelmasry** [medhatelmasry/voting-tool-cms#65]
When a user is logged in, he/she were able to see more navigation item on the top menu

**Comment by Jovan-23** [comment]
Finished. Waiting on pull request.

**Comment by Jovan-23** [comment]
Perry has merged my changes, this issue is now closed.

**Comment by Jovan-23** [comment]
User can only see the User Management navigation item if he/she is logged in with the Admin
