### ISSUE TITLE
Maps controller on the backend is broken

### ISSUE THREAD

**Issue by medhatelmasry** [medhatelmasry/voting-tool-cms#75]
The maps controller at the backend is not working properly

Test that this request returns response:

/maps?longitude=1234&latitude=-1234

**Comment by reneilpascua** [comment]
communicated with Ivan, as this issue is strongly connected to issue #52 "mapping tool needs to work properly"

**Comment by reneilpascua** [comment]
if @Ivan1120 does not respond by 17:00, i will need to take over this issue (#75) to further my fix for issue #52

**Comment by reneilpascua** [comment]
note: from the old project's mapscontroller, its endpoint specifies a **string** _location_ which i  understood to be 2 doubles separated by comma

example: ~/api/maps/-123.1011,49.204

![image](https://user-images.githubusercontent.com/38701391/79034811-c7164a80-7b6d-11ea-967f-f8209a092185.png)

**Comment by reneilpascua** [comment]
everything works now but keep in mind that the requests to this endpoint (as it is right now) must come in the form of {double longitude},{double latitude}

example: api/maps/-123.1139,49.2710

next steps:
- fix orderby issue (identified in the code for mapscontroller) going from EF2.2 to EF3.1
- decouple from azure key vault (already in progress)

note: this took a lot of research and debugging and, in my opinion, should be higher than a level 3. please refer to **pull request 93** for the resolution of this issue
